In [2]:
import numpy as np
import pandas as pd

In [3]:
dataset = pd.read_csv(r"D:\Mahe Basics\bank.csv")

In [4]:
dataset.head(2)

age     job  marital  education default  balance housing loan  contact  \
0   59  admin.  married  secondary      no     2343     yes   no  unknown   
1   56  admin.  married  secondary      no       45      no   no  unknown   

   day month  duration  campaign  pdays  previous poutcome deposit  
0    5   may      1042         1     -1         0  unknown     yes  
1    5   may      1467         1     -1         0  unknown     yes

In [4]:
dataset.isnull().any()

age          False
job          False
marital      False
education    False
default      False
balance      False
housing      False
loan         False
contact      False
day          False
month        False
duration     False
campaign     False
pdays        False
previous     False
poutcome     False
deposit      False
dtype: bool

In [8]:
x = dataset.iloc[:,0:9]
y = dataset.iloc[:,11:13]
z = dataset.iloc[:,14:16]

In [9]:
o = x.join(b)
o = o.join(z)

In [10]:
o = o.values
q = dataset.iloc[:,16:].values

In [11]:
o[0]

array([59, 'admin.', 'married', 'secondary', 'no', 2343, 'yes', 'no',
       'unknown', 1042, 1, 0, 'unknown'], dtype=object)

In [12]:
q

array([['yes'],
       ['yes'],
       ['yes'],
       ...,
       ['no'],
       ['no'],
       ['no']], dtype=object)

In [13]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

In [15]:
ct = ColumnTransformer([("one",OneHotEncoder(),[1,2,3,4,6,7,8,12])],remainder ="passthrough")
o = ct.fit_transform(o)

In [16]:
ct1 = ColumnTransformer([("one",OneHotEncoder(),[0])],remainder ="passthrough")
q = ct1.fit_transform(q)

In [17]:
o[0]

array([1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
       1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 1.0, 0.0, 0.0,
       0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 59, 2343, 1042, 1, 0], dtype=object)

In [18]:
q[80]

array([0., 1.])

In [19]:
from sklearn.model_selection import train_test_split
o_train,o_test, q_train,q_test = train_test_split(o,q,test_size = 0.2, random_state=0)

In [21]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
o_train = sc.fit_transform(o_train)
o_test = sc.fit_transform(o_test)

In [22]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [23]:
categorical = Sequential()

In [24]:
o_train.shape

(8929, 37)

In [25]:
q_train.shape

(8929, 2)

In [26]:
categorical.add(Dense( units= 37, kernel_initializer= "random_uniform", activation="relu"))

Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor


In [27]:
categorical.add(Dense( units= 74, kernel_initializer= "random_uniform", activation="relu"))

In [28]:
categorical.add(Dense( units= 2, kernel_initializer= "random_uniform", activation="softmax"))

In [29]:
categorical.compile(optimizer = "rmsprop", loss = "categorical_crossentropy", metrics=["accuracy"])

In [30]:
categorical.fit(o_train, q_train, epochs = 350)

Epoch 1/350
8929/8929 [==============================] - 1s 148us/sample - loss: 0.4796 - acc: 0.7790
Epoch 2/350
8929/8929 [==============================] - 1s 63us/sample - loss: 0.4169 - acc: 0.8132
Epoch 3/350
8929/8929 [==============================] - 1s 67us/sample - loss: 0.4104 - acc: 0.8196
Epoch 4/350
8929/8929 [==============================] - 1s 65us/sample - loss: 0.4073 - acc: 0.8197
Epoch 5/350
8929/8929 [==============================] - 1s 59us/sample - loss: 0.4052 - acc: 0.8211
Epoch 6/350
8929/8929 [==============================] - 1s 60us/sample - loss: 0.4018 - acc: 0.8246
Epoch 7/350
8929/8929 [==============================] - 1s 63us/sample - loss: 0.3983 - acc: 0.8210
Epoch 8/350
8929/8929 [==============================] - 0s 55us/sample - loss: 0.3962 - acc: 0.8272
Epoch 9/350
8929/8929 [==============================] - 1s 66us/sample - loss: 0.3951 - acc: 0.8261
Epoch 10/350
8929/8929 [==============================] - 1s 59us/sample - loss: 0.3935 - 

Epoch 81/350
8929/8929 [==============================] - 0s 56us/sample - loss: 0.3166 - acc: 0.8618
Epoch 82/350
8929/8929 [==============================] - 1s 72us/sample - loss: 0.3155 - acc: 0.8619
Epoch 83/350
8929/8929 [==============================] - 0s 55us/sample - loss: 0.3142 - acc: 0.8642
Epoch 84/350
8929/8929 [==============================] - 1s 58us/sample - loss: 0.3134 - acc: 0.8631
Epoch 85/350
8929/8929 [==============================] - 0s 55us/sample - loss: 0.3134 - acc: 0.8634
Epoch 86/350
8929/8929 [==============================] - 1s 61us/sample - loss: 0.3108 - acc: 0.8677
Epoch 87/350
8929/8929 [==============================] - 1s 77us/sample - loss: 0.3120 - acc: 0.8652
Epoch 88/350
8929/8929 [==============================] - 1s 70us/sample - loss: 0.3096 - acc: 0.8675
Epoch 89/350
8929/8929 [==============================] - 1s 65us/sample - loss: 0.3079 - acc: 0.8675
Epoch 90/350
8929/8929 [==============================] - 1s 85us/sample - loss: 0

8929/8929 [==============================] - 0s 53us/sample - loss: 0.2446 - acc: 0.8967
Epoch 161/350
8929/8929 [==============================] - 0s 54us/sample - loss: 0.2393 - acc: 0.8954
Epoch 162/350
8929/8929 [==============================] - 0s 53us/sample - loss: 0.2422 - acc: 0.8967
Epoch 163/350
8929/8929 [==============================] - 1s 56us/sample - loss: 0.2389 - acc: 0.8975
Epoch 164/350
8929/8929 [==============================] - 0s 54us/sample - loss: 0.2405 - acc: 0.8983
Epoch 165/350
8929/8929 [==============================] - 0s 56us/sample - loss: 0.2376 - acc: 0.8984
Epoch 166/350
8929/8929 [==============================] - 0s 55us/sample - loss: 0.2384 - acc: 0.8979
Epoch 167/350
8929/8929 [==============================] - 0s 55us/sample - loss: 0.2354 - acc: 0.8999
Epoch 168/350
8929/8929 [==============================] - 0s 54us/sample - loss: 0.2374 - acc: 0.9005
Epoch 169/350
8929/8929 [==============================] - 0s 55us/sample - loss: 0.235

8929/8929 [==============================] - 1s 62us/sample - loss: 0.1912 - acc: 0.9216
Epoch 240/350
8929/8929 [==============================] - 1s 59us/sample - loss: 0.1934 - acc: 0.9189
Epoch 241/350
8929/8929 [==============================] - 1s 68us/sample - loss: 0.1902 - acc: 0.9219
Epoch 242/350
8929/8929 [==============================] - 1s 69us/sample - loss: 0.1936 - acc: 0.9188
Epoch 243/350
8929/8929 [==============================] - 1s 64us/sample - loss: 0.1938 - acc: 0.9197
Epoch 244/350
8929/8929 [==============================] - 1s 86us/sample - loss: 0.1868 - acc: 0.9207
Epoch 245/350
8929/8929 [==============================] - 1s 70us/sample - loss: 0.1871 - acc: 0.9188
Epoch 246/350
8929/8929 [==============================] - 1s 92us/sample - loss: 0.1893 - acc: 0.9214
Epoch 247/350
8929/8929 [==============================] - 1s 64us/sample - loss: 0.1881 - acc: 0.9235
Epoch 248/350
8929/8929 [==============================] - 1s 68us/sample - loss: 0.185

8929/8929 [==============================] - 0s 53us/sample - loss: 0.1580 - acc: 0.9345
Epoch 319/350
8929/8929 [==============================] - 0s 55us/sample - loss: 0.1615 - acc: 0.9318
Epoch 320/350
8929/8929 [==============================] - 0s 55us/sample - loss: 0.1570 - acc: 0.9337
Epoch 321/350
8929/8929 [==============================] - 0s 55us/sample - loss: 0.1607 - acc: 0.9339
Epoch 322/350
8929/8929 [==============================] - 0s 54us/sample - loss: 0.1593 - acc: 0.9380
Epoch 323/350
8929/8929 [==============================] - 0s 54us/sample - loss: 0.1572 - acc: 0.9354
Epoch 324/350
8929/8929 [==============================] - 1s 66us/sample - loss: 0.1594 - acc: 0.9353
Epoch 325/350
8929/8929 [==============================] - 0s 55us/sample - loss: 0.1592 - acc: 0.9365
Epoch 326/350
8929/8929 [==============================] - 1s 58us/sample - loss: 0.1605 - acc: 0.9347
Epoch 327/350
8929/8929 [==============================] - 1s 59us/sample - loss: 0.152

In [31]:
an = categorical.predict(o_test)

In [32]:
an[0]

array([1., 0.], dtype=float32)

In [33]:
an [0] > 0.5

array([ True, False])

In [34]:
dataset.head(30)

age          job   marital  education default  balance housing loan  \
0    59       admin.   married  secondary      no     2343     yes   no   
1    56       admin.   married  secondary      no       45      no   no   
2    41   technician   married  secondary      no     1270     yes   no   
3    55     services   married  secondary      no     2476     yes   no   
4    54       admin.   married   tertiary      no      184      no   no   
5    42   management    single   tertiary      no        0     yes  yes   
6    56   management   married   tertiary      no      830     yes  yes   
7    60      retired  divorced  secondary      no      545     yes   no   
8    37   technician   married  secondary      no        1     yes   no   
9    28     services    single  secondary      no     5090     yes   no   
10   38       admin.    single  secondary      no      100     yes   no   
11   30  blue-collar   married  secondary      no      309     yes   no   
12   29   management   married   tertiary      no      199     yes  yes   
13   46  blue-collar    single   tertiary      no      460     yes   no   
14   31   technician    single   tertiary      no      703     yes   no   
15   35   management  divorced   tertiary      no     3837     yes   no   
16   32  blue-collar    single    primary      no      611     yes   no   
17   49     services   married  secondary      no       -8     yes   no   
18   41       admin.   married  secondary      no       55     yes   no   
19   49       admin.  divorced  secondary      no      168     yes  yes   
20   28       admin.  divorced  secondary      no      785     yes   no   
21   43   management    single   tertiary      no     2067     yes   no   
22   43   management  divorced   tertiary      no      388     yes   no   
23   43  blue-collar   married    primary      no     -192     yes   no   
24   37   unemployed    single  secondary      no      381     yes   no   
25   35  blue-collar    single  secondary      no       40     yes   no   
26   31   technician    single   tertiary      no       22     yes   no   
27   43  blue-collar    single  secondary      no        3     yes   no   
28   31       admin.   married  secondary      no      307     yes   no   
29   28  blue-collar    single  secondary      no      759     yes   no   

    contact  day month  duration  campaign  pdays  previous poutcome deposit  
0   unknown    5   may      1042         1     -1         0  unknown     yes  
1   unknown    5   may      1467         1     -1         0  unknown     yes  
2   unknown    5   may      1389         1     -1         0  unknown     yes  
3   unknown    5   may       579         1     -1         0  unknown     yes  
4   unknown    5   may       673         2     -1         0  unknown     yes  
5   unknown    5   may       562         2     -1         0  unknown     yes  
6   unknown    6   may      1201         1     -1         0  unknown     yes  
7   unknown    6   may      1030         1     -1         0  unknown     yes  
8   unknown    6   may       608         1     -1         0  unknown     yes  
9   unknown    6   may      1297         3     -1         0  unknown     yes  
10  unknown    7   may       786         1     -1         0  unknown     yes  
11  unknown    7   may      1574         2     -1         0  unknown     yes  
12  unknown    7   may      1689         4     -1         0  unknown     yes  
13  unknown    7   may      1102         2     -1         0  unknown     yes  
14  unknown    8   may       943         2     -1         0  unknown     yes  
15  unknown    8   may      1084         1     -1         0  unknown     yes  
16  unknown    8   may       541         3     -1         0  unknown     yes  
17  unknown    8   may      1119         1     -1         0  unknown     yes  
18  unknown    8   may      1120         2     -1         0  unknown     yes  
19  unknown    8   may       513         1     -1         0  unknown     yes  
20  unknown    8   